services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: match-analyze-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/matchdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    restart: always

  db:
    image: postgres:16
    container_name: match-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: matchdb
    ports:
      - "5432:5432"
    restart: always

  frontend:
    build:
      context: ./match-analyze-frontend
      dockerfile: Dockerfile
    container_name: match-analyze-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
